# Generated by Django 6.1.1 on 2026-09-22 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('medicamentos', '0002_medicamento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmacaoDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('tomado', 'Tomado'), ('nao_tomado', 'Não tomado')], default='pendente', max_length=20)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='horarios.horariomedicamento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='medicamentos.medicamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', 'horario'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'medicamento', 'horario', 'data'), name='dose_unica_por_horario_data')],
            },
        ),
    ]
