# Generated by Django 6.1.1 on 2026-09-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0002_medicamento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='medicamentos.medicamento')),
            ],
            options={
                'ordering': ['horario'],
            },
        ),
    ]
